_extends: .github

repository:
  name: circleci-orb-template
  description: template repository for publishing orbs
  homepage: https://github.com/bjd2385/circleci-orb-template

  # A comma-separated list of topics to set on the repository
  topics: circleci, orb
  private: false
