version: 2.1

parameters:
  workspace:
    type: string
    default: bjd2385

  orb-name:
    type: string
    default: github

orbs:
  orb-tools: circleci/orb-tools@11.1.2
  shellcheck: circleci/shellcheck@3.1.1
  circleci-cli: circleci/circleci-cli@0.1.9
  github-alpha: bjd2385/github@dev:alpha

executors:
  default:
    docker:
      - image: cimg/base:stable

commands:
  check_version:
    steps:
      - run:
          name: Install / upgrade the CircleCI CLI
          command: curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | sudo bash
      - run:
          name: Assert tag version is unpublished
          command: |
            [[ "$(circleci orb list << pipeline.parameters.workspace >> | grep "<< pipeline.parameters.workspace >>/<< pipeline.parameters.orb-name >>" | grep -oE "[0-9].[0-9].[0-9]")" != "${CIRCLE_TAG}" ]]

jobs:
  check_version:
    executor: default
    resource_class: small
    steps:
      - check_version

workflows:
  on-tag:
    jobs:
      - check_version:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

      - orb-tools/pack:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

      - orb-tools/publish:
          name: publish production orb
          enable-pr-comment: false
          vcs-type: << pipeline.project.type >>
          orb-name: << pipeline.parameters.workspace >>/<< pipeline.parameters.orb-name >>
          pub-type: production
          requires:
            - orb-tools/pack
            - check_version
          context:
            - development
            - orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

  on-merge:
    jobs:
      # Auto-increment minor tag to kick off on-tag workflow.
      - github-alpha/auto-increment-tag:
          ssh-key-fingerprint: "8a:59:7b:8c:a9:a8:f6:8b:98:7c:6d:c4:30:2a:38:ea"
          filters:
            branches:
              only: master

      # Generate a release from the latest tag.
      - github-alpha/generate-release:
          context: github
          filters:
            branches:
              only: master
          requires:
            - github-alpha/auto-increment-tag

  on-commit:
    jobs:
      # Run a bunch of tests against this repo
      - orb-tools/lint:
          filters:
            branches:
              ignore: master

      - orb-tools/pack:
          filters:
            branches:
              ignore: master

      - shellcheck/check:
          exclude: SC2148
          filters:
            branches:
              ignore: master

      - orb-tools/publish:
          name: publish development orb
          enable-pr-comment: true
          vcs-type: << pipeline.project.type >>
          orb-name: << pipeline.parameters.workspace >>/<< pipeline.parameters.orb-name >>
          pub-type: dev
          requires:
            - orb-tools/pack
            - orb-tools/lint
            - shellcheck/check
          context:
            - orb-publishing
            - github
          filters:
            branches:
              ignore: master
