version: 2.1

parameters:
  workspace:
    type: string
    default: bjd2385

  orb-name:
    type: string
    default: github

orbs:
  orb-tools: circleci/orb-tools@11.1.2
  shellcheck: circleci/shellcheck@3.1.1
  circleci-cli: circleci/circleci-cli@0.1.9
  github-alpha: bjd2385/github@dev:alpha

executors:
  default:
    docker:
      - image: cimg/base:stable

workflows:
  on-tag:
    jobs:
      - github-alpha/check-tag-version:
          workspace: << pipeline.parameters.workspace >>
          orb-name: << pipeline.parameters.orb-name >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

      - orb-tools/pack:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

      - orb-tools/publish:
          name: publish production orb
          enable-pr-comment: false
          vcs-type: << pipeline.project.type >>
          orb-name: << pipeline.parameters.workspace >>/<< pipeline.parameters.orb-name >>
          pub-type: production
          requires:
            - orb-tools/pack
            - github-alpha/check-tag-version
          context:
            - development
            - orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

  on-merge:
    jobs:
      - github-alpha/auto-increment-tag:
          ssh-key-fingerprint: 42:69:ed:28:5e:17:36:09:61:61:c3:8a:4d:5f:2f:d1
          filters:
            branches:
              only: master

      - github-alpha/generate-release:
          context: github
          filters:
            branches:
              only: master
          requires:
            - github-alpha/auto-increment-tag

  on-commit:
    jobs:
      - orb-tools/lint:
          filters:
            branches:
              ignore: master

      - orb-tools/pack:
          filters:
            branches:
              ignore: master

      - shellcheck/check:
          exclude: SC2148
          filters:
            branches:
              ignore: master

      - orb-tools/publish:
          name: publish development orb
          enable-pr-comment: true
          vcs-type: << pipeline.project.type >>
          orb-name: << pipeline.parameters.workspace >>/<< pipeline.parameters.orb-name >>
          pub-type: dev
          requires:
            - orb-tools/pack
            - orb-tools/lint
            - shellcheck/check
          context:
            - orb-publishing
            - github
          filters:
            branches:
              ignore: master

  # Keep development build alive.
  scheduled:
    jobs:
      - orb-tools/pack:
          filters:
            branches:
              only: master
      - orb-tools/publish:
          name: publish development orb
          enable-pr-comment: true
          vcs-type: << pipeline.project.type >>
          orb-name: << pipeline.parameters.workspace >>/<< pipeline.parameters.orb-name >>
          pub-type: dev
          requires:
            - orb-tools/pack
          context:
            - orb-publishing
            - github
          filters:
            branches:
              ignore: master
    triggers:
      - schedule:
          cron: "0 4 1 3,6,9,12 *"
          filters:
            branches:
              only:
                - master
