description: base default CircleCI executor.
parameters:
  tag:
    default: stable
    description: Default stable Ubuntu executor.
    type: string
docker:
  - image: "cimg/base:<< parameters.tag >>"
